server:
  port: 8080

spring:
  application:
    name: water-webgis-system
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_water_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
